# password default
app.password.default=user1234

# Secret key ต้องมีความยาวอย่างน้อย 256-bit (Base64 encoded string)
app.jwt.secret=c2VjcmV0S2V5Rm9ySldUVG9rZW5HZ4W5lcmF0aW9uTmVlZHNUb0JlTG9uZ0Vub3VnaEFiY2RlZmdoaWprbG1ub3A=
# หมดอายุใน 24 ชั่วโมง (86400000 ms)
app.jwt.expiration-milliseconds=86400000

# PostgreSQL Database Connection Config
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect //v.2

# Automatic Schema Creation
# update = ปรับเปลี่ยนโครงสร้างตารางตาม Entity อัตโนมัติ (เหมาะกับ dev)
# validate = ตรวจสอบโครงสร้างตารางโดยไม่แก้ไข
spring.jpa.hibernate.ddl-auto=update
# Flyway จะตรวจเช็คไฟล์ SQL ใหม่ๆ แล้วสั่งรันลง Database ให้อัตโนมัติ พร้อมบันทึกประวัติไว้ในตาราง flyway_schema_history
# true, false
spring.flyway.enabled=false